# Generated by Django 4.1 on 2022-08-31 20:34

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0003_cultures_and_heritages"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="wip",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="character",
            name="wip",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="culture",
            name="wip",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deathreason",
            name="wip",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="doctrine",
            name="wip",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dynasty",
            name="wip",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="era",
            name="wip",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ethnicity",
            name="wip",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ethos",
            name="wip",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="heritage",
            name="wip",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="holding",
            name="wip",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="holysite",
            name="wip",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="house",
            name="wip",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="innovation",
            name="wip",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="language",
            name="wip",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="law",
            name="wip",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="martialcustom",
            name="wip",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="menatarms",
            name="wip",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="namelist",
            name="wip",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="nickname",
            name="wip",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="province",
            name="wip",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="religion",
            name="wip",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="terrain",
            name="wip",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="title",
            name="wip",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tradition",
            name="wip",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trait",
            name="wip",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Localization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="date de création"),
                ),
                (
                    "modification_date",
                    models.DateTimeField(auto_now=True, verbose_name="date de modification"),
                ),
                ("key", models.CharField(max_length=128)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("fr", "French"),
                            ("de", "German"),
                            ("sp", "Spanish"),
                            ("ko", "Korean"),
                            ("ru", "Russian"),
                            ("zh", "Chinese"),
                        ],
                        default="en",
                        max_length=2,
                    ),
                ),
                ("text", models.TextField(blank=True)),
                ("wip", models.BooleanField(default=False)),
                (
                    "current_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="dernier utilisateur",
                    ),
                ),
            ],
            options={
                "unique_together": {("key", "language")},
            },
        ),
    ]
