# Generated by Django 4.1.3 on 2022-11-15 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0007_war_and_casus_belli"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterhistory",
            name="add_matrilineal_spouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matrilineal_spouses_added",
                to="database.character",
            ),
        ),
    ]
