# Generated by Django 4.2.1 on 2023-05-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0008_matrilineal_spouse"),
    ]

    operations = [
        migrations.AddField(
            model_name="innovation",
            name="unlock_buildings",
            field=models.ManyToManyField(blank=True, related_name="innovations", to="database.building"),
        ),
        migrations.AddField(
            model_name="innovation",
            name="unlock_casus_belli",
            field=models.ManyToManyField(blank=True, related_name="innovations", to="database.casusbelli"),
        ),
        migrations.AddField(
            model_name="innovation",
            name="unlock_laws",
            field=models.ManyToManyField(blank=True, related_name="innovations", to="database.law"),
        ),
        migrations.AddField(
            model_name="innovation",
            name="unlock_men_at_arms",
            field=models.ManyToManyField(blank=True, related_name="innovations", to="database.menatarms"),
        ),
        migrations.AddField(
            model_name="trait",
            name="ai_boldness",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trait",
            name="ai_compassion",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trait",
            name="ai_energy",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trait",
            name="ai_greed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trait",
            name="ai_honor",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trait",
            name="ai_rationality",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trait",
            name="ai_sociability",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trait",
            name="ai_vengefulness",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trait",
            name="ai_zeal",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trait",
            name="category",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="trait",
            name="has_tracks",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trait",
            name="liege_opinion",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trait",
            name="maximum_age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trait",
            name="minimum_age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trait",
            name="same_culture_opinion",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
