# Generated by Django 4.2.1 on 2023-05-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0009_innovations_and_traits"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="localization",
            name="id",
        ),
        migrations.AlterField(
            model_name="localization",
            name="key",
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
